dota2/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from django.urls import include, path
from heros.views import HeroListView
from .views import I18NView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


api_v1 = [
   path('authentication/v1/', include('authentication.urls.api_urls', namespace='api-auth')),
   path('heros/v1/', include('heros.api_urls', namespace='api-heros')),
]

api_v1_patterns = [
    path('api/', include(api_v1))
]


app_view_patterns = [
    path('heros/', include('heros.urls', namespace='heros')),
    path('auth/', include('authentication.urls.view_urls'), name='auth'),
]

urlpatterns = [
    path('', HeroListView.as_view(), name='index'),
    path('', include(api_v1_patterns)),
    path('', include(app_view_patterns)),
    path('i18n/<str:lang>/', I18NView.as_view(), name='i18n-switch'),
    path('admin/', admin.site.urls),
]

js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

handler404 = 'dota2.error_views.handler404'
handler500 = 'dota2.error_views.handler500'

urlpatterns += js_i18n_patterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
            + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path('^swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),

        re_path('^v2/swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/v2/', get_swagger_view("v2").with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/v2/', get_swagger_view("v2").with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

users/models/auth_device.py
from django.db  import models
from users.models import User
from django.utils.translation import ugettext_lazy as _


class AuthDevice(models.Model):
    ip = models.GenericIPAddressField(max_length=32, verbose_name=_('IP'), db_index=True)
    user = models.ForeignKey(User, verbose_name=_('User'), related_name='auth_devices', on_delete=models.deletion.CASCADE)

users/models/user.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import uuid
import base64
import string
import random
from collections import OrderedDict

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.core.cache import cache
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.shortcuts import reverse

from django.db.models import Q
import uuid
import datetime
from . import UserRole
from common.utils import get_signer, date_expired_default, get_logger

__all__ = ['User']

signer = get_signer()

logger = get_logger(__file__)


class User(AbstractUser):
    OTP_LEVEL_CHOICES = (
        (0, _('Disable')),
        (1, _('Enable')),
        (2, _("Force enable")),
    )
    SOURCE_LOCAL = 'local'
    SOURCE_LDAP = 'ldap'
    SOURCE_OPENID = 'openid'
    SOURCE_RADIUS = 'radius'
    SOURCE_CHOICES = (
        (SOURCE_LOCAL, 'Local'),
        (SOURCE_LDAP, 'LDAP/AD'),
        (SOURCE_OPENID, 'OpenID'),
        (SOURCE_RADIUS, 'Radius'),
    )

    CACHE_KEY_USER_RESET_PASSWORD_PREFIX = "_KEY_USER_RESET_PASSWORD_{}"

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    username = models.CharField(
        max_length=128, unique=True, verbose_name=_('Username')
    )
    name = models.CharField(max_length=128, verbose_name=_('Name'))
    email = models.EmailField(
        max_length=128, unique=True, verbose_name=_('Email')
    )
    groups = models.ManyToManyField(
        'users.UserGroup', related_name='users',
        blank=True, verbose_name=_('User group')
    )
    avatar = models.ImageField(
        upload_to="avatar", null=True, verbose_name=_('Avatar')
    )
    wechat = models.CharField(
        max_length=128, blank=True, verbose_name=_('Wechat')
    )
    phone = models.CharField(
        max_length=20, blank=True, null=True, verbose_name=_('Phone')
    )
    otp_level = models.SmallIntegerField(
        default=0, choices=OTP_LEVEL_CHOICES, verbose_name=_('MFA')
    )
    _otp_secret_key = models.CharField(max_length=128, blank=True, null=True)
    # Todo: Auto generate key, let user download
    _private_key = models.CharField(
        max_length=5000, blank=True, verbose_name=_('Private key')
    )
    _public_key = models.CharField(
        max_length=5000, blank=True, verbose_name=_('Public key')
    )
    comment = models.TextField(
        max_length=200, blank=True, verbose_name=_('Comment')
    )
    is_first_login = models.BooleanField(default=True)
    date_expired = models.DateTimeField(
        default=date_expired_default, blank=True, null=True,
        db_index=True, verbose_name=_('Date expired')
    )
    created_by = models.CharField(
        max_length=30, default='', verbose_name=_('Created by')
    )
    managed_groups = models.ManyToManyField(
        'users.UserGroup', related_name='managers',
        blank=True, verbose_name=_('Managed Group')
    )
    role = models.ForeignKey(
        'users.UserRole', on_delete=models.SET_NULL, null=True, verbose_name=_('Role')
    )
    telegram_chat_id = models.CharField(
        max_length=30, unique=True, blank=True, null=True
    )
    telegram_username = models.CharField(
        max_length=30, unique=True, blank=True, null=True, verbose_name=_('TelegramUsername')
    )
    enable_telegram_notification = models.BooleanField(
        default=False, verbose_name=_('Enable Telegram Notifcation')
    )
    source = models.CharField(
        max_length=30, default=SOURCE_LOCAL, choices=SOURCE_CHOICES, verbose_name=_('Source'),
    )
    date_password_last_updated = models.DateTimeField(
        auto_now_add=True, blank=True, null=True,
        verbose_name=_('Date password last updated')
    )
    cmd_filters = models.ManyToManyField('assets.CommandFilter', related_name='users', verbose_name=_("Command filter"), blank=True)


    user_cache_key_prefix = '_User_{}'

    def __str__(self):
        return '{0.name}({0.username})'.format(self)

    @property
    def cmd_filter_rules(self):
        from assets.models import CommandFilterRule
        rules = CommandFilterRule.objects.filter(
            filter__in=self.cmd_filters.all()
        ).distinct()
        return rules

    @property
    def password_raw(self):
        raise AttributeError('Password raw is not a readable attribute')

    #: Use this attr to set user object password, example
    #: user = User(username='example', password_raw='password', ...)
    #: It's equal:
    #: user = User(username='example', ...)
    #: user.set_password('password')
    @password_raw.setter
    def password_raw(self, password_raw_):
        self.set_password(password_raw_)

    def set_password(self, raw_password):
        self._set_password = True
        if self.can_update_password():
            return super().set_password(raw_password)
        else:
            error = _("User auth from {}, go there change password").format(self.source)
            raise PermissionError(error)

    def can_update_password(self):
        return self.is_local

    @property
    def otp_secret_key(self):
        return signer.unsign(self._otp_secret_key)

    @otp_secret_key.setter
    def otp_secret_key(self, item):
        self._otp_secret_key = signer.sign(item)

    def check_otp(self, code):
        from ..utils import check_otp_code
        return check_otp_code(self.otp_secret_key, code)

    def get_absolute_url(self):
        return reverse('users:user-detail', args=(self.id,))

    def is_public_key_valid(self):
        """
            Check if the user's ssh public key is valid.
            This function is used in base.html.
        """
        if self._public_key:
            return True
        return False

    @property
    def groups_display(self):
        return ' '.join(self.groups.all().values_list('name', flat=True))

    @property
    def role_display(self):
        return self.get_role_display()

    @property
    def source_display(self):
        return self.get_source_display()

    @property
    def is_expired(self):
        return False
        #if self.date_expired and self.date_expired < datetime.datetime.now():
        #if self.date_expired:
        #    return True
        #else:
        #    return False

    @property
    def is_valid(self):
        if self.is_active and not self.is_expired:
            return True
        return False

    @property
    def private_key(self):
        return signer.unsign(self._private_key)

    @private_key.setter
    def private_key(self, private_key_raw):
        self._private_key = signer.sign(private_key_raw)

    @property
    def public_key(self):
        return signer.unsign(self._public_key)

    @public_key.setter
    def public_key(self, public_key_raw):
        self._public_key = signer.sign(public_key_raw)

    @property
    def public_key_obj(self):
        class PubKey(object):
            def __getattr__(self, item):
                return ''
        if self.public_key:
            import sshpubkeys
            try:
                return sshpubkeys.SSHKey(self.public_key)
            except (TabError, TypeError):
                pass
        return PubKey()

    @property
    def is_superuser(self):
        return self.role.name == 'Admin'

    @property
    def is_superadmin(self):
        return self.role.name in ['Admin', 'SecondaryAdmin']

    @is_superuser.setter
    def is_superuser(self, value):
        if value is True:
            self.role = UserRole.objects.get(name='Admin')
        else:
            self.role = UserRole.objects.get(name='User')

    @property
    def is_applier(self):
        return self.role.name in ['GroupAdmin', 'User']

    @property
    def is_admin(self):
        return self.role.name in ['GroupAdmin', 'Admin', 'SecondaryAdmin']

    @property
    def is_groupadmin(self):
        return self.role.name == 'GroupAdmin'

    @property
    def is_commonuser(self):
        return self.role.name == 'User'

    @property
    def admin_orgs(self):
        from orgs.models import Organization
        return Organization.get_user_admin_orgs(self)

    @property
    def is_org_admin(self):
        if self.is_superuser or self.admin_orgs.exists():
            return True
        else:
            return False

    @property
    def is_app(self):
        return self.role.name == 'App'

    @property
    def is_staff(self):
        if self.is_authenticated and self.is_valid:
            return True
        else:
            return False

    @is_staff.setter
    def is_staff(self, value):
        pass

    @property
    def is_local(self):
        return self.source == self.SOURCE_LOCAL
    
    @property
    def date_password_expired(self):
        interval = settings.SECURITY_PASSWORD_EXPIRATION_TIME
        if self.date_password_last_updated:
            date_expired = self.date_password_last_updated + timezone.timedelta(days=int(interval))
        else:
            date_expired = timezone.now() + timezone.timedelta(days=int(interval))
        return date_expired

    @property
    def password_expired_remain_days(self):
        date_remain = self.date_password_expired - timezone.now()
        return date_remain.days

    @property
    def password_has_expired(self):
        if self.is_local and self.password_expired_remain_days < 0:
            return True
        return False

    @property
    def password_will_expired(self):
        if self.is_local and self.password_expired_remain_days < 5:
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.username
        if self.username == 'admin':
            self.role = UserRole.objects.get(name='Admin')
            self.is_active = True
        super().save(*args, **kwargs)
        self.expire_user_cache()

    @property
    def private_token(self):
        return self.create_private_token

users/models/utils.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 

from .user import User
from .group import UserGroup


def init_model():
    for cls in [User, UserGroup]:
        if getattr(cls, 'initial'):
            cls.initial()


def generate_fake():
    for cls in [User, UserGroup]:
        if getattr(cls, 'generate_fake'):
            cls.generate_fake()

users/views/group.py
# ~*~ coding: utf-8 ~*~
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.messages.views import SuccessMessageMixin

from common.utils import get_logger
from common.permissions import AdminUserRequiredMixin, AdminOrGroupAdminRequiredMixin, NavbarManagementMixin

from common.const import create_success_msg, update_success_msg
from orgs.utils import current_org
from ..models import User, UserGroup
from .. import forms

__all__ = ['UserGroupListView', 'UserGroupCreateView', 'UserGroupDetailView',
           'UserGroupUpdateView', 'UserGroupGrantedAssetView']
logger = get_logger(__name__)


class UserGroupListView(NavbarManagementMixin, TemplateView):
    template_name = 'users/user_group_list.html'

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('User group list')
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupCreateView(AdminUserRequiredMixin, SuccessMessageMixin, CreateView):
    model = UserGroup
    form_class = forms.UserGroupForm
    template_name = 'users/user_group_create_update.html'
    success_url = reverse_lazy('users:user-group-list')
    success_message = '<a href={url}> {name} </a> was created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.all()
        context.update({'app': _('Users'), 'action': _('Create user group'),
                        'users': users})
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        user_group = form.save()

        users_id_list = self.request.POST.getlist('users', [])
        managers_id_list = self.request.POST.getlist('managers', [])

        users = User.objects.filter(id__in=users_id_list)
        managers = User.objects.filter(id__in=managers_id_list)

        user_group.users.add(*users)
        user_group.managers.add(*managers)

        user_group.created_by = self.request.user.username or 'Admin'
        user_group.save()

        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        url = reverse_lazy('users:user-group-detail',
                           kwargs={'pk': self.object.id}
                           )
        return self.success_message.format(
            url=url, name=self.object.name
        )


class UserGroupUpdateView(AdminUserRequiredMixin, UpdateView):
    model = UserGroup
    form_class = forms.UserGroupForm
    template_name = 'users/user_group_create_update.html'
    success_url = reverse_lazy('users:user-group-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        obj = self.object
        users_id_list = self.request.POST.getlist('users', [])
        obj.users.set(User.objects.filter(id__in=users_id_list)) 

        if self.request.user.is_superadmin:
            managers_id_list = self.request.POST.getlist('managers', [])
            obj.managers.set(User.objects.filter(id__in=managers_id_list))

        obj.save()
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('Update user group'),

        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


                
class UserGroupDetailView(AdminOrGroupAdminRequiredMixin, DetailView):
    model = UserGroup
    context_object_name = 'user_group'
    template_name = 'users/user_group_detail.html'

    def get_context_data(self, **kwargs):
        # users = User.objects.exclude(id__in=self.object.users.all())
        users = current_org.get_org_users().exclude(id__in=self.object.users.all())

        context = {
            'app': _('Users'),
            'action': _('User group detail'),
            'users': users,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupGrantedAssetView(AdminUserRequiredMixin, DetailView):
    model = UserGroup
    template_name = 'users/user_group_granted_asset.html'
    context_object_name = 'user_group'
    object = None

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('User group granted asset'),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

users/templates/users/_base_otp.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title> {{ JMS_TITLE }} </title>
        <link rel="shortcut icon" href="{{ FAVICON_URL }}" type="image/x-icon">
		<link rel="stylesheet" href="{% static 'fonts/font_otp/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/otp.css' %}" />
        <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
        <script src="{% static "js/plugins/qrcode/qrcode.min.js" %}"></script>
        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
	</head>

	<body>
		<!--头部-->
		 <header>
		 	<div class="logo">
		 		<a href="{% url 'index' %}">
		 			<img src="{{ LOGO_URL }}" alt="" width="50px" height="50px"/>
		 		</a>
		 		<a href="{% url 'index' %}">{{ JMS_TITLE }}</a>
		 	</div>
		 	<div>
                <a href="{% url 'index' %}">{% trans 'Home page' %}</a>
		 		<b>丨</b>
                <a href="http://docs.jumpserver.org/zh/docs/">{% trans 'Docs' %}</a>
		 		<b>丨</b>
		 		<a href="https://www.github.com/jumpserver/">GitHub</a>
		 	</div>
		 </header>

		 <!--内容-->
		 <article>
            <div class="" style="text-align: center; margin-bottom: 50px">
                <h2>
                    {% block small_title %}
                    {% endblock %}
                </h2>
            </div>
		 	<div >
                <div class="verify">{% trans 'Security token validation' %}&nbsp;&nbsp;{% trans 'Account' %}&nbsp;<span>{{ user.username }}</span>&nbsp;&nbsp;{% trans 'Follow these steps to complete the binding operation' %}</div>
		 		<div class="line"></div>

                {% block content %}
                {% endblock %}
		 	</div>
		 </article>


        <footer>
            <div class="" style="margin-top: 100px;">
                {% include '_copyright.html' %}
            </div>
        </footer>

	</body>
</html>


users/templates/users/_select_user_modal.html
{% extends '_modal.html' %}
{% load i18n %}
{% block modal_class %}modal-lg{% endblock %}
{% block modal_id %}select_user_modal{% endblock %}
{% block modal_title%}{% trans "Please Select User" %}{% endblock %}
{% block modal_body %}
<table class="table table-striped table-bordered table-hover " id="select_user_table" >
    <thead>
        <tr>
            <th class="text-center">
                <div class="checkbox checkbox-default"><input id="" type="checkbox" class="ipt_check_all"><label></label></div>
            </th>
            <th class="text-center">{% trans 'Name' %}</th>
            <th class="text-center">{% trans 'Username' %}</th>
            <th class="text-center">{% trans 'Role' %}</th>
            <th class="text-center">{% trans 'User group' %}</th>
            <th class="text-center">{% trans 'Asset num' %}</th>
            <th class="text-center">{% trans 'Active' %}</th>
        </tr>
    </thead>
</table>
{% endblock %}
{% block modal_confirm_id %}btn_select_user{% endblock %}

users/templates/users/_user.html
{% extends '_base_create_update.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}
{% block form %}
    {% if form.non_field_errors %}
         <div class="alert alert-danger">
            {{ form.non_field_errors }}
         </div>
    {% endif %}
    <form method="post" class="form-horizontal" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>{% trans 'Account' %}</h3>
        {% bootstrap_field form.name layout="horizontal" %}
        {% bootstrap_field form.username layout="horizontal" %}
        {% bootstrap_field form.email layout="horizontal" %}
        {% bootstrap_field form.groups layout="horizontal" %}

        <div class="hr-line-dashed"></div>

        <h3>{% trans 'Auth' %}</h3>
        {% block password %}{% endblock %}
        {% bootstrap_field form.otp_level layout="horizontal" %}

        <div class="hr-line-dashed"></div>
        {% block navbar_dashboard %} {% endblock %}

        <div class="hr-line-dashed"></div>
        <h3>{% trans 'Security and Role' %}</h3>
        {% bootstrap_field form.user_role layout="horizontal" %}
        <div class="form-group {% if form.date_expired.errors %} has-error {% endif %}" id="date_5">
            <label for="{{ form.date_expired.id_for_label }}" class="col-sm-2 control-label">{{ form.date_expired.label }}</label>
            <div class="col-sm-9">
                <div class="input-group date">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    {% if form.errors %}
                    <input id="{{ form.date_expired.id_for_label }}" name="{{ form.date_expired.html_name }}" type="text" class="form-control"  value="{{ form.date_expired.value }}">
                    {% else %}
                    <input id="{{ form.date_expired.id_for_label }}" name="{{ form.date_expired.html_name }}" type="text" class="form-control"  value="{{ form.date_expired.value|date:'Y-m-d H:i' }}">
                    {% endif %}
                </div>
                <span class="help-block ">{{ form.date_expired.errors }}</span>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <h3>{% trans 'Profile' %}</h3>
        {% bootstrap_field form.phone layout="horizontal" %}
        {% bootstrap_field form.wechat layout="horizontal" %}
        {% bootstrap_field form.comment layout="horizontal" %}
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                <button class="btn btn-white" type="reset">{% trans 'Reset' %}</button>
                <button id="submit_button" class="btn btn-primary" type="submit">{% trans 'Submit' %}</button>
            </div>
        </div>
    </form>

{% endblock %}
{% block custom_foot_js %}
    <script src="{% static 'js/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript" src='{% static "js/plugins/daterangepicker/moment.min.js" %}'></script>
    <script type="text/javascript" src='{% static "js/plugins/daterangepicker/daterangepicker.min.js" %}'></script>
    <link rel="stylesheet" type="text/css" href={% static "css/plugins/daterangepicker/daterangepicker.css" %} />

    <script>
        var dateOptions = {
            singleDatePicker: true,
            showDropdowns: true,
            timePicker: true,
            timePicker24Hour: true,
            autoApply: true,
            locale: {
                format: 'YYYY-MM-DD HH:mm'
            }
        };
        $(document).ready(function () {
            $('.select2').select2();
            $('#id_date_expired').daterangepicker(dateOptions);
            var mfa_radio = $('#id_otp_level');
            mfa_radio.addClass("form-inline");
            mfa_radio.children().css("margin-right","15px")
        })
    </script>
{% endblock %}

users/templates/users/_user_import_modal.html
{% extends '_import_modal.html' %}
{% load i18n %}

{% block modal_title%}{% trans "Import users" %}{% endblock %}

{% block import_modal_download_template_url %}{% url "api-users:user-list" %}{% endblock %}

users/templates/users/_user_update_modal.html
{% extends '_update_modal.html' %}
{% load i18n %}

{% block modal_title%}{% trans "Update user" %}{% endblock %}

users/templates/users/first_login_done.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap3 %}


{% block custom_head_css_js %}
{{ wizard.form.media }}
<link href="{% static 'css/plugins/steps/jquery.steps.css' %}" rel="stylesheet">
{% endblock %}
{% block first_login_message %}{% endblock %}

{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
              <h5>{% trans 'First Login' %}</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="alert alert-success" id="messages">
                    {% trans 'Welcome to use techdog, visit ' %}
                    <a href="{{ user_guide_url }}" target="_blank">{% trans 'Use guide' %}</a> {% trans ' for more information' %}
                </div>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}


{% block custom_foot_js %}
<script>
$(document).on('click', ".fl_goto", function(){
  var $form = $('#fl_form');
  $('<input />', {'name': 'wizard_goto_step', 'value': $(this).data('goto'), 'type': 'hidden'}).appendTo($form);
  $form.submit();
  return false;
}).on('click', '#fl_submit', function(){
  $('#fl_form').submit();
  return false;
})
</script>
{% endblock %}

users/templates/users/user_password_authentication.html
{% extends 'users/_base_otp.html' %}
{% load static %}
{% load i18n %}

{% block small_title %}
    {% trans 'Authenticate' %}
{% endblock %}

{% block content %}
    <form class="" role="form" method="post" action="">
        {% csrf_token %}

        <div class="form-input">
            <input type="text" class="" name="{{ form.username.html_name }}" value="{{ form.username.value }}" readonly="readonly" required="">
        </div>

        <div class="form-input">
            <input type="password" class="" name="{{ form.password.html_name }}" placeholder="{% trans 'Password' %}" required="">
        </div>

        <button type="submit" class="next">{% trans 'Next' %}</button>

        {% if 'password' in form.errors %}
            <p class="red-fonts">{{ form.password.errors.as_text }}</p>
        {% endif %}

    </form>
{% endblock %}